name: On Call Notify

on:
  push: 
    branches:
      - main

jobs:
  notify:
    name: 'Notifier'
    runs-on: ubuntu-latest
    steps:
      - name: Fetch schedules
        id: schedules
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.opsgenie.com/v2/schedules'
          method: 'GET'
          customHeaders: '{"Authorization": "GenieKey ${{ secrets.OPS_GENIE_KEY }}"}'
      - name: Show Response
        run: |
          echo ${{ steps.schedules.outputs.response }}
          echo ${{ steps.schedules.outputs.headers }}
          echo ${{ steps.schedules.outputs.status }}
          echo ${{ fromJson(steps.schedules.outputs.response).field_you_want_to_access }}