name: On Call Notify

on:
  push: 
    branches:
      - main

env:
  payments_schedule_id: f8c270c0-a11e-48cc-8715-39b8b4456b4d

jobs:
  notify:
    name: 'Notifier'
    runs-on: ubuntu-latest
    steps:
      - name: Fetch on call
        id: schedules
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.opsgenie.com/v2/schedules/${{env.payments_schedule_id}}/on-calls'
          method: 'GET'
          customHeaders: '{"Authorization": "GenieKey ${{ secrets.OPS_GENIE_KEY }}"}'
      - name: Map Responder
        id: responder
        run: |
          echo ${{ steps.schedules.outputs.response }}
          echo "${{ fromJson(steps.schedules.outputs.response).data.onCallParticipants[0].name }}" >> "$GITHUB_OUTPUT"
      - name: Send slack message
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: 'C02BSHKTVHR'
          SLACK_ICON: https://avatars.githubusercontent.com/u/47012371?s=150&v=4
          SLACK_MESSAGE: '[Test] ${{ steps.responder.outputs }} está on-call essa semana'
          SLACK_TITLE: '[Test] Payments On Call'
          SLACK_USERNAME: 'on-call-bot'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_DEPLOY }}
