name: (#Bugs) On Call Notify 

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *" 

jobs:
  notify:
    uses: ./.github/workflows/on-call-template.yml
    secrets: inherit
    with:
      channelId: CEZ6B64UE  # bugs
      title: 'Plantão'
      userMessage: 'estará atuando como apoio técnico essa semana'
      footerMessage: "Por favor não entrem em contato direto (DM), use o canal ou abra uma SI"