name: On Call Notify

on:
  push: 
    branches:
      - main

env:
  payments_schedule_id: f8c270c0-a11e-48cc-8715-39b8b4456b4d
  payments_channel: C02BSHKTVHR

jobs:
  prepare:
    name: 'Prepare Schedules'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.save.outputs.json }}
    steps:
      - name: Fetch schedules
        id: schedules
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.opsgenie.com/v2/schedules'
          method: 'GET'
          customHeaders: '{"Authorization": "GenieKey ${{ secrets.OPS_GENIE_KEY }}"}'
      - name: Store matrix
        id: save
        uses: nickofthyme/object-remap@v1
        with:
          include.*.team: ${{ toJSON(fromJson(steps.schedules.outputs.response).data.*.ownerTeam.name) }}
          include.*.scheduleId: ${{ toJSON(fromJson(steps.schedules.outputs.response).data.*.id) }}
          include.*.scheduleName: ${{ toJSON(fromJson(steps.schedules.outputs.response).data.*.name) }}
  notifier:
    name: 'Notify Slack'
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
      fail-fast: false
    steps:
      - if: ${{ contains(matrix.scheduleName, 'on-call') }}
        name: Log infos
        run: echo "team - ${{ matrix.team }} | scheduleName - ${{ matrix.scheduleName }} | scheduleId - ${{ matrix.scheduleId }}"
      - if: ${{ contains(matrix.scheduleName, 'on-call') }}
        name: Fetch on call
        id: oncall
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.opsgenie.com/v2/schedules/${{matrix.scheduleId}}/on-calls'
          method: 'GET'
          customHeaders: '{"Authorization": "GenieKey ${{ secrets.OPS_GENIE_KEY }}"}'
      - if: ${{ contains(matrix.scheduleName, 'on-call') }}
        name: Send slack message
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ${{env.payments_channel}}
          SLACK_ICON: https://avatars.githubusercontent.com/u/47012371?s=150&v=4
          SLACK_TITLE: '${{matrix.team}} On Call'
          SLACK_MESSAGE: '${{ fromJson(steps.schedules.outputs.response).data.onCallParticipants[0].name }} está on-call essa semana'
          SLACK_USERNAME: 'on-call-bot'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_DEPLOY }}
          MSG_MINIMAL: true
          SLACK_MSG_AUTHOR: kovihq
          SLACK_FOOTER: '<https://kovihq.app.opsgenie.com/settings/schedule/detail/${{matrix.scheduleId}}|Para mais detalhes>'
