name: (#Team-engineers) On Call Notify 

on:
  schedule:
    - cron: "0 12 * * 1" 

jobs:
  notify:
    uses: ./.github/workflows/on-call-template.yml
    secrets: inherit
    with:
      channelId: CEW7CLZP1 # team-engineers
      title: 'On Call'
      userMessage: 'está on-call essa semana'