name: (#Bugs) On Call Notify 

on:
  workflow_dispatch:
  schedule:
    - cron: "0 09 * * *" 

jobs:
  notify:
    uses: ./.github/workflows/on-call-template.yml
    secrets: inherit
    with:
      channelId: CEZ6B64UE  # bugs
      title: 'Plantão'
      userMessage: 'estará atuando como apoio técnico essa semana'
      footer: ''